/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VentasRouteImport } from './routes/ventas'
import { Route as ReportesRouteImport } from './routes/reportes'
import { Route as InventarioRouteImport } from './routes/inventario'
import { Route as ConfiguracionRouteImport } from './routes/configuracion'
import { Route as CajaRouteImport } from './routes/caja'
import { Route as AperturaRouteImport } from './routes/apertura'
import { Route as IndexRouteImport } from './routes/index'

const VentasRoute = VentasRouteImport.update({
  id: '/ventas',
  path: '/ventas',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportesRoute = ReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => rootRouteImport,
} as any)
const InventarioRoute = InventarioRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracionRoute = ConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => rootRouteImport,
} as any)
const CajaRoute = CajaRouteImport.update({
  id: '/caja',
  path: '/caja',
  getParentRoute: () => rootRouteImport,
} as any)
const AperturaRoute = AperturaRouteImport.update({
  id: '/apertura',
  path: '/apertura',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apertura': typeof AperturaRoute
  '/caja': typeof CajaRoute
  '/configuracion': typeof ConfiguracionRoute
  '/inventario': typeof InventarioRoute
  '/reportes': typeof ReportesRoute
  '/ventas': typeof VentasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apertura': typeof AperturaRoute
  '/caja': typeof CajaRoute
  '/configuracion': typeof ConfiguracionRoute
  '/inventario': typeof InventarioRoute
  '/reportes': typeof ReportesRoute
  '/ventas': typeof VentasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apertura': typeof AperturaRoute
  '/caja': typeof CajaRoute
  '/configuracion': typeof ConfiguracionRoute
  '/inventario': typeof InventarioRoute
  '/reportes': typeof ReportesRoute
  '/ventas': typeof VentasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apertura'
    | '/caja'
    | '/configuracion'
    | '/inventario'
    | '/reportes'
    | '/ventas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apertura'
    | '/caja'
    | '/configuracion'
    | '/inventario'
    | '/reportes'
    | '/ventas'
  id:
    | '__root__'
    | '/'
    | '/apertura'
    | '/caja'
    | '/configuracion'
    | '/inventario'
    | '/reportes'
    | '/ventas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AperturaRoute: typeof AperturaRoute
  CajaRoute: typeof CajaRoute
  ConfiguracionRoute: typeof ConfiguracionRoute
  InventarioRoute: typeof InventarioRoute
  ReportesRoute: typeof ReportesRoute
  VentasRoute: typeof VentasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ventas': {
      id: '/ventas'
      path: '/ventas'
      fullPath: '/ventas'
      preLoaderRoute: typeof VentasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reportes': {
      id: '/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof ReportesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventario': {
      id: '/inventario'
      path: '/inventario'
      fullPath: '/inventario'
      preLoaderRoute: typeof InventarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracion': {
      id: '/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof ConfiguracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caja': {
      id: '/caja'
      path: '/caja'
      fullPath: '/caja'
      preLoaderRoute: typeof CajaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apertura': {
      id: '/apertura'
      path: '/apertura'
      fullPath: '/apertura'
      preLoaderRoute: typeof AperturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AperturaRoute: AperturaRoute,
  CajaRoute: CajaRoute,
  ConfiguracionRoute: ConfiguracionRoute,
  InventarioRoute: InventarioRoute,
  ReportesRoute: ReportesRoute,
  VentasRoute: VentasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
